### ISSUE TITLE
Mod repost request 

### ISSUE THREAD

**Issue by mcBegins2Snow** [Lykrast/JETIF#6]
Hello,author. Your mod is very good! I want to repost it to a Chinese minecraft forum, its name is MCBBS( http://www.mcbbs.net ), and I'll link a source URL to curseforge.
By the way, I've added Chinese translation files successfully, please agree this request. :)

**Comment by Lykrast** [comment]
If you:

* Link the curseforge page properly on your post
* Link the curseforge download and not a reuploaded one

Then yes feel free to do it.

**Comment by mcBegins2Snow** [comment]
Thanks!
